[package]
name = "names-cli"
version = "0.9.0"
authors = ["Fletcher Nichol <fnichol@nichol.ca>"]
license = "MIT"
repository = "https://github.com/fnichol/names.git"
homepage = "https://github.com/fnichol/names.git"
description = """
A program to generate random names that look like 'used-jellyfish'.
"""

[[bin]]
name = "names"

[dependencies]
# pending a release which includes https://github.com/kbknapp/clap-rs/pull/257
clap = { git = "https://github.com/kbknapp/clap-rs", rev = "40104af" }
names = { path = ".." }
